import libs    = libtensorrt%libs{nvinfer} \
                 libtensorrt%libs{nvonnxparser}
# make sure executables are importable
import trtexec = libtensorrt%exe{trtexec}

testscript{trtexec}@./: test = $trtexec
./: testscript{trtexec}@./ $trtexec

./: exe{driver}: cxx{**} $libs
